name: CI-CD-Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Backend Image
        run: docker build -t virtualverse/mean-backend:latest ./backend

      - name: Build Frontend Image
        run: docker build -t virtualverse/mean-frontend:latest ./frontend

      - name: Push Backend Image
        run: docker push virtualverse/mean-backend:latest

      - name: Push Frontend Image
        run: docker push virtualverse/mean-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd mean-app
            docker-compose pull
            docker-compose up -d
